### ISSUE TITLE
GTFS ???

### ISSUE THREAD

**Issue by sansamy** [bendardenne/MMM-stib2#1]
Bonsoir merci pour le module , il est top.
par contre les gtfs je ne trouve pas , la liste des arrêts avec les noms et id si vous pouvez m aider pour ca, merci aussi savez vous quel est le temps max que le système accès pour la clé  ou si on peut mettre une valeur pour ne pas devoir régénérer.  Bonne soiree

**Comment by sansamy** [comment]
Autant pour moi je devais juste redémarrer et ca s est affiché,ça donne super bien  par contre les gtfs je ne trouve pas la liste des arrêts avec les noms et id si vous pouvez m aider pour ca, merci

**Comment by bendardenne** [comment]
En mettant -1 la clef est illimitée dans le temps.

Pour les GTFS, voir là: 
https://www.stib-mivb.be/irj/go/km/docs/resource/OpenData/de4f0aa3-f061-4499-8eae-9ba6a1cede18.pdf

**Comment by sansamy** [comment]
Genial et merci pour la rapidité de reponse

**Comment by sansamy** [comment]
Je pensais que c etait une liste d arret ? En cliquant sur le lien on parle d un fichier rar de 25 mo mais j ai ca lorsque je clique sur le lien ???

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ams:fault xmlns:ams="http://wso2.org/apimanager/security">
<ams:code>900902</ams:code>
<ams:message>Missing Credentials</ams:message>
<ams:description>
Required OAuth credentials not provided. Make sure your API invocation call has a header: "Authorization: Bearer ACCESS_TOKEN"
</ams:description>
</ams:fault>

**Comment by bendardenne** [comment]
La liste d'arrêts est dans le zip. Cliquer sur le lien ne suffit pas, il faut passer le token dans la requête. Dans le PDF il y a un exemple pour le faire avec curl.

**Comment by sansamy** [comment]
Ok donc j ouvre LxTerminal je copie colle l exemple en mettant mon "accès tokken" et après je trouve ou les arrêts que je veux? (Id et nom) dsl je suis pas un pro en informatique

**Comment by bendardenne** [comment]
C'est ça, il faut copier coller ça :

`curl -k -X GET --header "Accept: application/zip" --header "Authorization:Bearer TOKEN" -o ./gtfs.zip "https://opendata-api.stib-mivb.be/Files/2.0/Gtfs"`

Et ça enregistra la réponse dans un fichier "gtfs.zip" dans le répertoire courant.

**Comment by sansamy** [comment]
Ok, juste pour pas faire de bêtise après les modifications je dois copier coller dans la console juste après raspberry ou je dois saisir le module stib2 avant?

**Comment by bendardenne** [comment]
Saisir le module ?

Faut juste ouvrir un terminal, et envoyer la commande et c'est bon normalement.

**Comment by sansamy** [comment]
Zip bien télécharger je fais extraire ici , rien ne se passe, j ai mis sur une usb pour l extraire ds mon pc mais ça met (insérer le dernier disque de l ensemble multi volumes  et cliquer sur ok....) si j essaye kd meme d extraire (fichier endommagé ou manquant) j ai répéter l operation en vainc

**Comment by bendardenne** [comment]
Chez moi ça marche sans soucis, tu as du faire une mauvaise manipulation. Voilà le fichier:

[stops.txt](https://github.com/bendardenne/MMM-stib2/files/5211574/stops.txt)

Attention un même arrêt peut avoir plusieurs IDs (souvent il y en a au moins deux, un pour chaque sens de la ligne).

**Comment by sansamy** [comment]
Ok je vais tchequer tout ça,  j ai tout fais pareil mais a la fin le zip ne voulait rien savoir,  merci pour ta patiente en tous cas et pour le fichier cest sympa!

**Comment by sansamy** [comment]
Au cas ou les numéros d arret sont noter en bas de la page de l horaire sur le site stib , plus simple a chercher . Merci

**Comment by bendardenne** [comment]
> Au cas ou les numéros d arret sont noter en bas de la page de l horaire sur le site stib , plus simple a chercher . Merci

Ah ok, bien observé, c'est plus simple en effet !

**Comment by sansamy** [comment]
Aussi j ai essye 2 arrêts d une meme ligne , malheureusement ça ne vas pas

**Comment by bendardenne** [comment]
> Aussi j ai essye 2 arrêts d une meme ligne , malheureusement ça ne vas pas

Ça c'est intentionnel. Si tu mets deux arrêts proches l'un de l'autre avec par exemple 4 lignes qui passent aux deux arrêts, ça fait trop d'information dupliquée et ça prend beaucoup de place pour rien.

L'ordre des arrêts dans la configuration c'est importante, le premier arrêt qui reçoit une ligne affichera les horaires pour cette ligne.

**Comment by sansamy** [comment]
J ai 2 arrêts de la même ligne a 13 arret d ecart l in de l autre sur 1 des 2 y a 2 bus et l autre 1 seul
