### ISSUE TITLE
Showing "no data"

### ISSUE THREAD

**Issue by maxencekyz** [bendardenne/MMM-stib2#2]
Hello @bendardenne ,

This is my config:

> {
			module: "MMM-stib2", // Transport de Bruxelles
			position: "bottom_left",
			config: {
			  apiToken: "xxxxxxxx",
			  stops: [
			  {
				name: "EDDY MERCKX",
				id: ["8651"]
			  },
			  ]
			}
		},

I tried multiples stations ID and name. I refreshed the access token. Nothing changes. I've got the "no data" sentence on my mirror.
Furthermore, I checked the console, there is no problem.

Any issue to solve this problem ?
Thanks !
Have a wonderful week end,

- Max

**Comment by bendardenne** [comment]
Unfortunately, I no longer have a magic mirror, so this module is currently unmaintained. It's possible that the STIB API has changed for example.

Please make sure you are running the browser without http2 support as STIB's http2 setup was (last I checked) buggy (as per the README file).  If the browser console shows CORS errors, this is likely the problem.

If that doesn't solve the problem, inspect the network requests that are made to the STIB API and check the responses.

**Comment by maxencekyz** [comment]
Thank you Bendardenne, I tried your tips, it didn't work.
I'm sure it came from the API itself. 
Thanks for your time,
Have a nice day :))

**Comment by bendardenne** [comment]
FYI the project was recently updated to work with the latest STIB API, which was probably the issue you were facing.
