### ISSUE TITLE
No data (with valid API key)

### ISSUE THREAD

**Issue by novalore** [bendardenne/MMM-stib2#3]
Hi, 
Does someone still use this module? It looks great in the screenshot and it would be ideal for my mirror, but I can't get anything from the API and there are no logs. I have the impression that the endpoints changed. Check https://data.stib-mivb.be/explore/dataset/waiting-time-rt-production/api/ for example.

In case anyone will answer, the following is my configuration entry for the module:
`{
                         module: "MMM-stib2",
                         position: "bottom_center",
                         header: "STIB-MIVB",
                         config: {
                         apiToken: "XXX", //here I added my Api key from https://stibmivb.opendatasoft.com/account/api-keys/
                         stops: [{
                                 name: "Jourdan",
                                 id: ["3921", "3922", "3158B"]
                                 }, {
                                 name: "Etangs",
                                 id: ["1777B", "1733", "3160", "3572"]
                                 }]
                         }
                 },`

**Comment by bendardenne** [comment]
Unfortunately the glass on my mirror broke some years ago and I didn't have the courage to rebuild it. So I'm not using this anymore.

If you want to use this, I'm afraid you will need to figure out the new STIB API. I have no idea how different (or not) it is from the previous API.

**Comment by bendardenne** [comment]
That being said. I'm starting to think that I should make another one now as I have a bit more free time...
I will see if I can't quickly fix the API calls this weekend, it might just be a minor change.

**Comment by bendardenne** [comment]
I've just made some quick changes to get it to work again. Didn't test a whole lot, but you could give it a try. You might run into some API limits if you configure too many stops, but with the config you pasted above, it seems like it should work. 

BTW apparently there's no api token needed for the API anymore, it seems to just work without any authentication :shrug:

**Comment by bendardenne** [comment]
Ah, thanks for figuring that out. I couldn't find any documentation about it on the STIB website. 

I didn't see a pull request, but I pushed some changes for using the token.
