### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by KristjanESPERANTO** [bendardenne/MMM-stib2#4]
In [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I am working on, tags are displayed for each module. These are read from the package.json. So far there are no keywords in the package.json of your module. It would be nice if you could add some. [Here you can see an example of a package.json with keywords.](https://github.com/jalibu/MMM-NINA/blob/04896f1ed9139059ea1b9d24ada4161d70e13030/package.json#L10)

This would be my suggestion:

```json
  "keywords": [
    "MagicMirror",
    "STIB",
    "Brussels",
    "public transport"
  ],
```

**Comment by bendardenne** [comment]
Added your suggested keywords, thanks

**Comment by KristjanESPERANTO** [comment]
Thank you! Now your module looks nice on the module list :smiley:
